DROP TABLE IF EXISTS segments;
DROP TABLE IF EXISTS objects;
DROP TABLE IF EXISTS flow_collection;
DROP TABLE IF EXISTS flow_tags;
DROP TABLE IF EXISTS flows;
DROP TABLE IF EXISTS source_tags;
DROP TABLE IF EXISTS sources;
DROP EXTENSION IF EXISTS btree_gist;
