// Command genunionbridges emits a companion Go file of `MarshalJSON`
// passthrough methods to compensate for oapi-codegen issue #1250:
//
//	https://github.com/oapi-codegen/oapi-codegen/issues/1250
//
// oapi-codegen's strict-server generates response types as
//
//	type FooResponse Underlying
//
// which is a type *definition*, not an alias (no `=`). Type definitions do
// NOT inherit methods from their underlying type, so if `Underlying`
// relies on a hand-written `MarshalJSON` — as it does for polymorphic
// unions (discriminated `oneOf`/`anyOf`, stored in an unexported
// `union json.RawMessage` field) and for schemas with
// `additionalProperties` (which use a `json:"-"`-tagged map exposed via a
// custom marshaler) — the strict response wrapper silently loses the
// marshaler. `json.Encoder` falls back to default struct encoding and
// emits `{}` or a body missing its additional-properties map.
//
// This tool scans the generated file and, for every `type X Y` where `Y`
// has its own `MarshalJSON`, emits
//
//	func (r X) MarshalJSON() ([]byte, error) { return Y(r).MarshalJSON() }
//
// in a sibling file. The compensating methods are in the same package as
// the generated types so Go's method-set rules apply: `json.Encoder` now
// finds the marshaler and calls it.
//
// Usage:
//
//	go run ./tools/genunionbridges \
//	    -in  gen/api/opentams.gen.go \
//	    -out gen/api/opentams_json_bridges.gen.go \
//	    -pkg api
//
// The tool is idempotent; rerunning produces byte-identical output for an
// unchanged input.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"sort"
	"text/template"
)

type bridge struct {
	Named      string
	Underlying string
}

func main() {
	in := flag.String("in", "", "input generated oapi-codegen Go file")
	out := flag.String("out", "", "output bridge file path")
	pkg := flag.String("pkg", "api", "package name for the output file")
	flag.Parse()

	if *in == "" || *out == "" {
		log.Fatal("genunionbridges: -in and -out are required")
	}

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, *in, nil, parser.SkipObjectResolution)
	if err != nil {
		log.Fatalf("genunionbridges: parse %s: %v", *in, err)
	}

	marshalBearing := collectMarshalJSONReceivers(f)
	bridges := collectDefinitionAliases(f, marshalBearing)

	sort.Slice(bridges, func(i, j int) bool { return bridges[i].Named < bridges[j].Named })

	source, err := render(*pkg, bridges)
	if err != nil {
		log.Fatalf("genunionbridges: render: %v", err)
	}

	if err := os.WriteFile(*out, source, 0o600); err != nil {
		log.Fatalf("genunionbridges: write %s: %v", *out, err)
	}

	fmt.Printf("genunionbridges: wrote %d bridge methods to %s\n", len(bridges), *out)
	for _, b := range bridges {
		fmt.Printf("  - (%s) MarshalJSON -> %s.MarshalJSON\n", b.Named, b.Underlying)
	}
}

// collectMarshalJSONReceivers returns the set of type names in `f` that
// declare their own `MarshalJSON` method (value or pointer receiver).
func collectMarshalJSONReceivers(f *ast.File) map[string]bool {
	out := map[string]bool{}
	for _, decl := range f.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || fn.Recv == nil || len(fn.Recv.List) != 1 {
			continue
		}
		if fn.Name.Name != "MarshalJSON" {
			continue
		}
		switch rt := fn.Recv.List[0].Type.(type) {
		case *ast.Ident:
			out[rt.Name] = true
		case *ast.StarExpr:
			if id, ok := rt.X.(*ast.Ident); ok {
				out[id.Name] = true
			}
		}
	}
	return out
}

// collectDefinitionAliases returns every `type X Y` (NOT `type X = Y`)
// where Y is in `marshalBearing`. Those are exactly the types that lost
// Y's MarshalJSON and need a bridge.
func collectDefinitionAliases(f *ast.File, marshalBearing map[string]bool) []bridge {
	var out []bridge
	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.TYPE {
			continue
		}
		for _, s := range gd.Specs {
			ts, ok := s.(*ast.TypeSpec)
			if !ok {
				continue
			}
			if ts.Assign != token.NoPos {
				continue
			}
			id, ok := ts.Type.(*ast.Ident)
			if !ok {
				continue
			}
			if !marshalBearing[id.Name] {
				continue
			}
			if ts.Name.Name == id.Name {
				continue
			}
			// From oapi-codegen v2.7.0 the generator emits MarshalJSON for
			// some of these named types itself. Bridging one of those would
			// redeclare the method, so skip any type that already has one.
			if marshalBearing[ts.Name.Name] {
				continue
			}
			out = append(out, bridge{Named: ts.Name.Name, Underlying: id.Name})
		}
	}
	return out
}

var tpl = template.Must(template.New("b").Parse(`// Code generated by tools/genunionbridges. DO NOT EDIT.
//
// Compensates for oapi-codegen issue #1250: strict-server response types
// are defined as ` + "`type X Y`" + ` which strips Y's custom MarshalJSON.
// The passthroughs below cast back to the underlying type so its
// MarshalJSON is invoked by encoding/json. Without them, polymorphic
// union responses serialise as ` + "`{}`" + ` and additionalProperties-bearing
// responses silently drop their additional properties.

package {{ .Pkg }}
{{ range .Bridges }}
func (r {{ .Named }}) MarshalJSON() ([]byte, error) {
	return {{ .Underlying }}(r).MarshalJSON()
}
{{ end }}`))

func render(pkg string, bridges []bridge) ([]byte, error) {
	var buf bytes.Buffer
	if err := tpl.Execute(&buf, struct {
		Pkg     string
		Bridges []bridge
	}{pkg, bridges}); err != nil {
		return nil, fmt.Errorf("template execute: %w", err)
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt:\n%s\nerror: %w", buf.String(), err)
	}
	return formatted, nil
}
